### ISSUE TITLE
A few dropdown issues

### ISSUE THREAD

**Issue by Brendan-csel** [LXSMNSYC/solid-headless#3]
First off, thanks for making a great start with these components.  I appreciate it is early days.

I've just started doing some testing based on the Dropdown menu example and have made a few notes:
1. With the menu open, pressing up/down on a long page causes the page to scroll (in addition to selecting the next menu item).
2. Also related to up/down, it seems disabled menu items aren't skipped.
3. Also, when pressing escape, should the PopoverButton get focused?  The doesn't seem to be what happens at the moment.
4. It also seems common behaviour for the Dropdown to automatically close itself when a non-disabled item is chosen (clicked/Enter/Space)

**Comment by LXSMNSYC** [comment]
1. Yes this has been a long issue. Not sure but the current workaround for this is. I'll probably do a research
2. Might have missed that, to fix.
3. I'm sure it should refocus on the last focused element (before opening). 
4. I was sure it should close itself but probably there was some regression. I'll check it out again

**Comment by LXSMNSYC** [comment]
@Brendan-csel after re-evaluation here are some of my thoughts

Primarily, the dropdown-menu example is supposed to be just a Popover + Menu demo. The thing about this is that there's no predefined behavior for when these two are combined, and thus it is left to the user implementation to control the visual state of the dropdown. 

1. I was thinking of the Listbox behavior mistakenly. This is the correct behavior due to how focus works with scrolling.
2. According to the WAI-ARIA definition of Menu:

> Disabled menu items are focusable but cannot be activated.

So the current behavior is correct.

3. This might be fixable.

4. This is left for user to implement.

**Comment by Brendan-csel** [comment]
Thanks @LXSMNSYC.

I'm trying out some other options but for the sake of completely documenting this, here is a [stackblitz link](https://stackblitz.com/edit/github-efe3mt?file=src/main.tsx)

And a capture of me focusing the button, pressing down a few times (and not getting past the disabled item), then pressing escape.
![GgDTKJvthf](https://user-images.githubusercontent.com/1744490/141227573-ebbeee78-9c35-403c-abff-f33ee0d9fd40.gif)
